name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          pip install playwright
          python -m playwright install

      # Run tests
      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html
        continue-on-error: true

      # Upload test results as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
