name: Playwright Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for testing

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python (if using Python for Playwright testing)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Install Python 3.9 (modify if you use a different version)

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install pytest-html  # Install pytest-html for generating HTML report
          pip install playwright  # Install Playwright
          python -m playwright install  # Install Playwright browsers (Chromium, WebKit, Firefox)

      # Run Playwright tests and generate HTML report
      - name: Run tests
        run: |
          pytest --html=./pseries/report.html --self-contained-html  # Save report in pseries folder
        continue-on-error: true  # Continue even if tests fail (for uploading the artifact)

      # Add debug step to list files in the directory
      - name: List files in the directory
        run: |
          ls -al pseries/  # List the files to verify the report file exists

      # Upload the test report as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v2.2.3  # Use the stable version v2.2.3
        with:
          name: test-report  # Name of the artifact in GitHub Actions
          path: pseries/report.html  # Correct path to the generated report inside the repository
